{{ 
    config(
        materialized='table', 
        alias='STG_OFP_POOLS',
	tags=["stg-ofp"]
    ) 
}}

WITH FINAL AS (
    SELECT
		POOLID AS POOL_ID,
		POOLTYPEID AS POOL_TYPE_ID,

        	CASE 
		WHEN POOLTYPEID IN (1,2,3,4,20,31) AND SPORTID = 1 THEN 'NFL PICK ''EM'
		WHEN POOLTYPEID IN (1,2,3,4,20,31) AND SPORTID = 5 THEN 'CFB PICK ''EM'
 		ELSE PT.POOL_TYPE END AS LEAGUE_TYPE,

		SPORTID AS SPORT_ID,
		S.DESCRIPTION AS LEAGUE_CATEGORY,
		POOLACTIVE AS POOL_ACTIVE,
		DATECREATED AS DATE_CREATED,
		SEASONID AS SEASON_ID,
		POOLMASTERID AS POOLMASTER_ID,
		'OFP' AS SOURCE
    FROM
        {{ source('OFP_DBO', 'OFPPOOLS') }} M
	JOIN {{ ref('stg_ofp_allsports') }} S ON M.SPORTID = S.SPORT_ID
	JOIN {{ ref('stg_ofp_pool_types') }} PT ON M.POOLTYPEID = PT.POOL_TYPE_ID
)

SELECT * FROM FINAL