version: 2
sources:
  - name: RYP_NFL_2020_2021
    database: sources
    tables:
      - name: PICKS_NFL_SQUARES
      - name: NFL_SQUARES_SETTINGS
      - name: GAMES_NFL
      - name: NFL_SQUARES_ENTRIES
      - name: NFL_PICKEM_ENTRIES
      - name: PICKS_WITH_SPREAD
      - name: NFL_SURVIVOR_ENTRIES
      - name: PICKS_SURVIVOR
