{{ 
    config(
        materialized='table', 
        alias='STG_RYP_ORDER_TRANSACTION',
	tags=["stg-ryp"]
    ) 
}}

WITH ORDER_TRANSACTION AS (
    SELECT
        RYPTRANSACTIONID AS RYP_TRANSACTION_ID,
        AUTHNETREQUESTXML AS AUTHNET_REQUEST_XML,
        ORDERID AS ORDER_ID,
        AUTHNETRESPONSECODE AS AUTHNET_RESPONSE_CODE,
        AUTHNETRESPONSEREASONCODE AS AUTHNET_RESPONSE_REASON_CODE,
        AUTHNETRESPONSEXML AS AUTHNET_RESPONSE_XML,
        AUTHNETTRANSACTIONID AS AUTHNET_TRANSACTION_ID,
        TRANSACTIONDATETIME AS TRANSACTION_DATE_TIME,
        'RYP' AS SOURCE

    FROM
        {{ source('RYP_RUNYOURPOOL_DBO', 'ORDERTRANSACTION') }}
)

SELECT * FROM ORDER_TRANSACTION
