{{ 
    config(
        materialized='table', 
        alias='STG_RYP_ORDERS',
	tags=["stg-ryp"]
    ) 
}}

WITH O AS (
    SELECT 
		ORDERID AS ORDER_ID,
		MEMBERID AS MEMBER_ID,
		TAXAMOUNT AS TAX_AMOUNT,
		COUPONAMOUNT AS COUPON_AMOUNT,
		STATUSID AS STATUS_ID,
		DATETIMECREATED AS DATE_TIME_CREATED,
		COUNTRYVIAIP AS COUNTRY_VIA_IP,
		PAIDRYPTRANSACTIONID AS PAID_RYP_TRANSACTION_ID,
		PROCESSORID AS PROCESSOR_ID,
		COUPONCODE AS COUPON_CODE,
		SUBTOTALAMOUNT AS SUB_TOTAL_AMOUNT,
		REMOTEIP AS REMOTE_IP,
		'RYP' as SOURCE
		
    FROM 
    	{{ source('RYP_RUNYOURPOOL_DBO', 'ORDER') }}
)
SELECT * FROM O