{{ 
    config(
        materialized='table', 
        alias='METRIC_NNAU_BY_LEAGUE_CATEGORY'
    ) 
}}

WITH FIRST_PICK_DATE AS (
    SELECT 
        DISTINCT MEMBER_EMAIL,
        LEAGUE_CATEGORY,
        MIN(PICK_DATE) AS FIRST_PICK_DATE
    FROM {{ ref('fact_active_entries') }} AE
    WHERE SOURCE = 'RYP' 
    GROUP BY 1,2
),

NEW_USERS AS (
    SELECT 
        COUNT (DISTINCT MEMBER_EMAIL) AS NEW_USER_COUNT,
        LEAGUE_CATEGORY,
        FISCAL_PERIOD,
        FISCAL_QUARTER
    FROM FIRST_PICK_DATE AE
        JOIN {{ ref('dates') }} D ON AE.FIRST_PICK_DATE::DATE = D.DATE_DAY
    GROUP BY LEAGUE_CATEGORY, FISCAL_PERIOD, FISCAL_QUARTER
    ORDER BY FISCAL_PERIOD DESC, FISCAL_QUARTER DESC
),

CHURNED_USERS AS (
    SELECT 
        COUNT (DISTINCT MEMBER_EMAIL) AS CHURNED_USER_COUNT,
        LEAGUE_CATEGORY,
        FISCAL_PERIOD,
        FISCAL_QUARTER
    FROM {{ ref('fact_member_status_by_league_category') }} M
        JOIN {{ ref('dates') }} D ON M.CHURNED_DATE::DATE = D.DATE_DAY
    WHERE IS_CHURNED = 1
        AND SOURCE = 'RYP' 
    GROUP BY LEAGUE_CATEGORY, FISCAL_PERIOD, FISCAL_QUARTER
    ORDER BY FISCAL_PERIOD DESC, FISCAL_QUARTER DESC
),

UNCHURNED_USERS AS (
    SELECT 
        COUNT (DISTINCT MEMBER_EMAIL) AS UNCHURNED_USER_COUNT,
        LEAGUE_CATEGORY,
        FISCAL_PERIOD,
        FISCAL_QUARTER
    FROM {{ ref('fact_member_unchurned_by_league_category') }} 
    WHERE SOURCE = 'RYP' 
    GROUP BY LEAGUE_CATEGORY, FISCAL_PERIOD, FISCAL_QUARTER
    ORDER BY FISCAL_PERIOD DESC, FISCAL_QUARTER DESC
),
FINAL AS (
    SELECT
        NU.LEAGUE_CATEGORY,
        NU.FISCAL_PERIOD,
        NU.FISCAL_QUARTER,
        IFNULL(NEW_USER_COUNT,0) NEW_USER_COUNT,
        IFNULL(CHURNED_USER_COUNT,0) CHURNED_USER_COUNT,
        IFNULL(UNCHURNED_USER_COUNT,0) AS REACTIVATED_USERS,
        IFNULL(NEW_USER_COUNT,0) - IFNULL(CHURNED_USER_COUNT,0) + IFNULL(UNCHURNED_USER_COUNT,0) AS NNAU
    
    FROM NEW_USERS NU
        LEFT JOIN CHURNED_USERS CU ON NU.FISCAL_PERIOD = CU.FISCAL_PERIOD AND NU.FISCAL_QUARTER = CU.FISCAL_QUARTER AND CU.LEAGUE_CATEGORY = NU.LEAGUE_CATEGORY
        LEFT JOIN UNCHURNED_USERS UU ON NU.FISCAL_PERIOD = UU.FISCAL_PERIOD AND NU.FISCAL_QUARTER = UU.FISCAL_QUARTER AND UU.LEAGUE_CATEGORY = NU.LEAGUE_CATEGORY
    ORDER BY FISCAL_PERIOD DESC, FISCAL_QUARTER DESC
    )
SELECT * FROM FINAL
ORDER BY FISCAL_PERIOD DESC, FISCAL_QUARTER