{{ 
    config(
        materialized='table', 
        alias='STG_RYP_BACK_LOG',
	tags=["stg-ryp"]
    ) 
}}

WITH FINAL AS (
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'CFB_BACK_LOG') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'MLB_BACK_LOG') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NBA_BACK_LOG') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NHL_BACK_LOG') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NHL_BACK_LOG_2') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'PGA_BACK_LOG') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NFL_BACK_LOG') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NFL_BACK_LOG_2') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NFL_BACK_LOG_3') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'NFL_BACK_LOG_4') }}
	UNION
	SELECT * FROM {{ source('BACK_LOG_ENTRIES', 'MULTI_SPORT_BACK_LOG') }}
)

SELECT * FROM FINAL
