{{ 
    config(
        materialized='table', 
        alias='STG_RYP_VIP_PICK_LOG_PGA',
	tags=["vip_picks"]
    ) 
}}

WITH PICK_LOG_PGA AS (
    SELECT
        M.MEMBER_ID,
        T.LEAGUE_ID,
        P.ENTRY_ID,
        LC.DATASOURCE_NAME AS LEAGUE_CATEGORY,
        LT.DESCRIPTION AS LEAGUE_TYPE,
        DATEADD('MS', P.TIMESTAMP, '1970-01-01') AS PICK_TIMESTAMP,
	P.PICKS AS PICKS,
	PT.NAME_SHORT AS TOURNAMENT_NAME,
        'RYP' AS PRODUCT

    FROM {{ source('RYP_PICK_LOGS', 'PICK_LOG_PGA') }} AS P
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'TEAMS') }} AS T ON
            P.TEAM_ID = T.TEAM_ID
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} AS M ON
            T.MEMBER_ID = M.MEMBER_ID
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'LEAGUE_TYPES') }} AS LT ON
            LT.LEAGUE_TYPE_ID = P.LEAGUE_TYPE_ID
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'LEAGUE_CATEGORIES') }} AS LC ON
            LT.LEAGUE_CATEGORY_ID = LC.LEAGUE_CATEGORY_ID
    INNER JOIN
        {{ source('RYP_PGA_DBO', 'PGA_TOURNAMENTS') }} AS PT ON
            P.PICK_PERIOD = PT.PGA_TOURNAMENT_ID
)

SELECT * FROM PICK_LOG_PGA
