{{ 
    config(
        materialized='table', 
        alias='STG_RYP_PICK_LOG_CBB',
	tags=["stg-ryp"]
    ) 
}}

WITH PICK_LOG_CBB AS (
    SELECT
	    {{ dbt_utils.surrogate_key(['P.TEAM_ID', 'P.TIMESTAMP']) }} as PICK_ID,
        M.MEMBER_ID,
        M.MEMBER_EMAIL,
        T.TEAM_ID,
        T.LEAGUE_ID,
        P.IP_ADDRESS,
        P.LEAGUE_TYPE_ID,
        P.ENTRY_ID,
        P.SHEET AS SHEET_ID,
        P.PICK_PERIOD,
        'RYP' AS PRODUCT,
        LC.DATASOURCE_NAME AS LEAGUE_CATEGORY,
        LT.DESCRIPTION AS LEAGUE_TYPE,
        DATEADD('MS', P.TIMESTAMP, '1970-01-01') AS PICK_TIMESTAMP,
        prod.public.parse_useragent(TO_ARRAY(P.USER_AGENT)) AS USER_AGENT,
        CURRENT_TIMESTAMP AS ETL_AT

    FROM {{ source('RYP_PICK_LOGS', 'PICK_LOG_CBB') }} AS P
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'TEAMS') }} AS T ON
            P.TEAM_ID = T.TEAM_ID
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} AS M ON
            T.MEMBER_ID = M.MEMBER_ID
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'LEAGUE_TYPES') }} AS LT ON
            LT.LEAGUE_TYPE_ID = P.LEAGUE_TYPE_ID
    INNER JOIN
        {{ source('RYP_RUNYOURPOOL_DBO', 'LEAGUE_CATEGORIES') }} AS LC ON
            LT.LEAGUE_CATEGORY_ID = LC.LEAGUE_CATEGORY_ID
),
--HISTORICAL
HISTORICAL AS (
	SELECT DISTINCT
		NULL AS PICK_ID,
		T.MEMBER_ID,
		M.MEMBER_EMAIL,
		P.TEAM_ID,
		P.LEAGUE_ID,
		NULL AS IP_ADDRESS,
		19 AS LEAGUE_TYPE_ID,
		E.ENTRY_ID,    
		P.SHEET_ID,
		NULL AS PICK_PERIOD,
		'RYP' AS PRODUCT,
		'CBB' AS LEAGUE_CATEGORY,
		'MARCH MADNESS SQUARES' AS LEAGUE_TYPE,
		'2022-03-17' AS PICK_TIMESTAMP,
		 NULL AS USER_AGENT,
		 CURRENT_TIMESTAMP AS ETL_AT

	FROM {{ source('RYP_CBB_DBO', 'PICKS_MADNESS_SQUARES') }} AS P
		JOIN {{ source('RYP_CBB_DBO', 'CBB_SQUARES_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2022_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID

	WHERE P.TEAM_ID IS NOT NULL

	UNION

	SELECT DISTINCT 
		NULL AS PICK_ID,
		T.MEMBER_ID,
		M.MEMBER_EMAIL,
		P.TEAM_ID,
		P.LEAGUE_ID,
		NULL AS IP_ADDRESS,
		5 AS LEAGUE_TYPE_ID,
		E.ENTRY_ID,    
		P.SHEET_ID,
		NULL AS PICK_PERIOD,
		'RYP' AS PRODUCT,
		'CBB' AS LEAGUE_CATEGORY,
		'MEN''S NCAA BRACKET' AS LEAGUE_TYPE,
		'2022-03-17' AS PICK_TIMESTAMP,
		 NULL AS USER_AGENT,
		 CURRENT_TIMESTAMP AS ETL_AT

	FROM {{ source('RYP_CBB_DBO', 'PICKS_NCAA_BB_PICK8') }} AS P
		JOIN {{ source('RYP_CBB_DBO', 'CBB_PICK8_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2022_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID
	
	UNION

	SELECT DISTINCT 
		null as PICK_ID,
		t.member_id,
		M.MEMBER_EMAIL,
		p.team_id,
		P.LEAGUE_ID,
		null as IP_ADDRESS,
		40 as league_type_id,
		e.entry_id,    
		p.sheet_id,
		null AS PICK_PERIOD,
		'RYP' AS PRODUCT,
		'CBB' AS LEAGUE_CATEGORY,
		'Head to Head' AS LEAGUE_TYPE,
		'2022-03-17' as pick_timestamp,
		 null AS USER_AGENT,
		 CURRENT_TIMESTAMP AS ETL_AT

	FROM {{ source('RYP_CBB_DBO', 'CBB_H2H_PICKS') }} AS P
		JOIN {{ source('RYP_CBB_DBO', 'CBB_H2H_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2022_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID
		
	UNION   
   
    SELECT DISTINCT 
        NULL AS PICK_ID,
        T.MEMBER_ID,
        M.MEMBER_EMAIL,
        P.TEAM_ID,
        P.LEAGUE_ID,
        NULL AS IP_ADDRESS,
        4 AS LEAGUE_TYPE_ID,
        E.ENTRY_ID,    
        P.SHEET_ID,
        NULL AS PICK_PERIOD,
        'RYP' AS PRODUCT,
        'CBB' AS LEAGUE_CATEGORY,
        'MEN''S NCAA BRACKET' AS LEAGUE_TYPE,
        '2021-03-19' AS PICK_TIMESTAMP,
         NULL AS USER_AGENT,
         CURRENT_TIMESTAMP AS ETL_AT
 	
	FROM {{ source('RYP_CBB_2022', 'PICKS_NCAA_BB') }} AS P
		JOIN {{ source('RYP_CBB_2022', 'CBB_BRACKET_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2021_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID   

	UNION

    SELECT DISTINCT 
        NULL AS PICK_ID,
        T.MEMBER_ID,
        M.MEMBER_EMAIL,
        P.TEAM_ID,
        P.LEAGUE_ID,
        NULL AS IP_ADDRESS,
        18 AS LEAGUE_TYPE_ID,
        E.ENTRY_ID,    
        P.SHEET_ID,
        NULL AS PICK_PERIOD,
        'RYP' AS PRODUCT,
        'CBB' AS LEAGUE_CATEGORY,
        'NCAA SURVIVOR' AS LEAGUE_TYPE,
        '2021-03-19' AS PICK_TIMESTAMP,
         NULL AS USER_AGENT,
         CURRENT_TIMESTAMP AS ETL_AT
         
 	FROM {{ source('RYP_CBB_2022', 'PICKS_NCAA_BB_SURVIVOR') }} AS P
		JOIN {{ source('RYP_CBB_2022', 'CBB_SURVIVOR_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2021_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID   
		
		
UNION

    SELECT DISTINCT 
        NULL AS PICK_ID,
        T.MEMBER_ID,
        M.MEMBER_EMAIL,
        P.TEAM_ID,
        P.LEAGUE_ID,
        NULL AS IP_ADDRESS,
        19 AS LEAGUE_TYPE_ID,
        E.ENTRY_ID,    
        P.SHEET_ID,
        NULL AS PICK_PERIOD,
        'RYP' AS PRODUCT,
        'CBB' AS LEAGUE_CATEGORY,
        'MARCH MADNESS SQUARES' AS LEAGUE_TYPE,
        '2021-03-19' AS PICK_TIMESTAMP,
         NULL AS USER_AGENT,
         CURRENT_TIMESTAMP AS ETL_AT
     
	FROM {{ source('RYP_CBB_2022', 'PICKS_MADNESS_SQUARES') }} AS P
		JOIN {{ source('RYP_CBB_2022', 'CBB_SQUARES_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2021_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID   

    WHERE P.TEAM_ID IS NOT NULL
		
UNION


    SELECT DISTINCT 
        NULL AS PICK_ID,
        T.MEMBER_ID,
        M.MEMBER_EMAIL,
        P.TEAM_ID,
        P.LEAGUE_ID,
        NULL AS IP_ADDRESS,
        5 AS LEAGUE_TYPE_ID,
        E.ENTRY_ID,    
        P.SHEET_ID,
        NULL AS PICK_PERIOD,
        'RYP' AS PRODUCT,
        'CBB' AS LEAGUE_CATEGORY,
        'NCAA PICK X' AS LEAGUE_TYPE,
        '2021-03-19' AS PICK_TIMESTAMP,
         NULL AS USER_AGENT,
         CURRENT_TIMESTAMP AS ETL_AT

	FROM {{ source('RYP_CBB_2022', 'PICKS_NCAA_BB_PICK8') }} AS P
		JOIN {{ source('RYP_CBB_2022', 'CBB_PICK8_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2021_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID  
		
		
UNION

    SELECT DISTINCT 
        NULL AS PICK_ID,
        T.MEMBER_ID,
        M.MEMBER_EMAIL,
        E.TEAM_ID,
        P.LEAGUE_ID,
        NULL AS IP_ADDRESS,
        40 AS LEAGUE_TYPE_ID,
        E.ENTRY_ID,    
        E.SHEET_ID,
        NULL AS PICK_PERIOD,
        'RYP' AS PRODUCT,
        'CBB' AS LEAGUE_CATEGORY,
        'HEAD TO HEAD' AS LEAGUE_TYPE,
        '2021-03-19' AS PICK_TIMESTAMP,
         NULL AS USER_AGENT,
         CURRENT_TIMESTAMP AS ETL_AT
 
	FROM {{ source('RYP_CBB_2022', 'CBB_H2H_PICKS') }} AS P
		JOIN {{ source('RYP_CBB_2022', 'CBB_H2H_ENTRIES') }} E ON E.ENTRY_ID = P.ENTRY_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_2021_05_01_DBO', 'TEAMS') }} T ON E.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID  

UNION

    select distinct 
        NULL AS PICK_ID,
        T.MEMBER_ID,
        M.MEMBER_EMAIL,
        E.TEAM_ID,
        P.LEAGUE_ID,
        NULL AS IP_ADDRESS,
        47 AS LEAGUE_TYPE_ID,
        E.ENTRY_ID,    
        E.SHEET_ID,
        null AS PICK_PERIOD,
        'RYP' AS PRODUCT,
        'CBB' AS LEAGUE_CATEGORY,
        'Women''s NCAA Bracket' AS LEAGUE_TYPE,
        '2021-03-19' as pick_timestamp,
         null AS USER_AGENT,
         CURRENT_TIMESTAMP AS ETL_AT		
 
	FROM {{ source('RYP_CBB_2022', 'WOMENS_BRACKET_PICKS') }} AS P
		JOIN {{ source('RYP_CBB_2022', 'WOMENS_BRACKET_ENTRIES') }} E ON E.TEAM_ID = P.TEAM_ID AND E.SHEET_ID = P.SHEET_ID
		JOIN {{ source('RYP_RUNYOURPOOL_2021_05_01_DBO', 'TEAMS') }} T ON P.TEAM_ID = T.TEAM_ID 
		JOIN {{ source('RYP_RUNYOURPOOL_DBO', 'MEMBERS') }} M ON M.MEMBER_ID = T.MEMBER_ID  
)

SELECT * FROM PICK_LOG_CBB
UNION
SELECT * FROM HISTORICAL
